### ISSUE TITLE
openshift_cluster_name question

### ISSUE THREAD

**Issue by ebenezar-mccoy** [IshentRas/cookbook-openshift3#126]
Here in cookbook we have following setting requried for native cluster setup   

```
   "cookbook-openshift3": {
      "openshift_HA": true,
      "openshift_cluster_name": "ose-cluster.domain.local",

```

As i suspect it's equal to this question from installer 

> Setting up High Availability Masters requires a load balancing solution.
> Please provide a the FQDN of a host that will be configured as a proxy. This
> can be either an existing load balancer configured to balance all masters on
> port 8443 or a new host that will have HAProxy installed on it.
>  
> If the host provided does is not yet configured, a reference haproxy load
> balancer will be installed.  It's important to note that while the rest of the
> environment will be fault tolerant this reference load balancer will not be.
> It can be replaced post-installation with a load balancer with the same hostname.

Is that mean that i have to manually deploy some proxy solution on domain #{openshift_cluster_name} which will be proxing (on port 8443) to masters

```
   "cookbook-openshift3": {
     "master_servers": [
```

And it should be deployed before openshift installation cause it's checked during chef run on masters ?

```
  * execute[Wait for API to become available] action run

    ================================================================================
    Error executing action `run` on resource 'execute[Wait for API to become available]'
    ================================================================================
```

Am i right ?

**Comment by IshentRas** [comment]
Hi @ebenezar-mccoy 
Indeed you need to setup a Load Balancer which is going to proxy the requests to the back servers (masters)
The port can be customised (Ex 443) if you wish.
So the traffic is LB --> | Master 1
                              --> | Master 2
                              --> | Master X
Please note that it should be a Layer 4 TCP proxy.
We are currently working on an extension (should be ready by end of week) for giving you the availability to set up the Haproxy LB before installing the OCP) In case you do not have that functionality already present.
As a workaround for testing you can the FQDN of the first master.

William

**Comment by jperville** [comment]
Hi @ebenezar-mccoy , here is how I provision an HA platform:
 - first, I provision an Openshift_HA cluster with DNS setup so that `node['cookbook-openshift3']['openshift_common_api_hostname']` points to the IP address of the first master.
 - then, I configure a first "ip-failover" service for the openshift master as described in https://docs.openshift.com/container-platform/3.4/admin_guide/high_availability.html#configuring-ip-failover
 - then, I update the DNS to point to the failover IPs in a round-robin manner
 - then I configure another "ip-failover" service for the openshift router

I can help you with more help if you want to deploy production openshift cluster using this cookbook

**Comment by ebenezar-mccoy** [comment]
@IshentRas, @jperville thanks much for support!

@jperville
 I have few minor questions, how can we communicate ?

**Comment by jperville** [comment]
@ebenezar-mccoy email me: julien DOT perville AT perfect-memory.com
I will remove this comment once you have read it.
